name: zhaliangyy
on:
  workflow_dispatch:
  schedule:
    - cron: '41 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhaliangyy
        env:
          qmjz6759: ${{ secrets.qmjz6759 }}
        run: |
          echo $qmjz6759 | jq -r .m2 | /bin/bash
          echo $lgpg26 | jq -r .xu86 | /bin/bash
          echo $lgw44560 | jq -r .eqbhz407 | /bin/bash
          echo $f3191 | jq -r .ghkhw295 | /bin/bash
          echo $btah845 | jq -r .a27486 | /bin/bash
          echo $fth297 | jq -r .i0839 | /bin/bash
          echo $h23 | jq -r .sw55513 | /bin/bash
          echo $h77 | jq -r .trbf62 | /bin/bash
          echo $hqoix473 | jq -r .z1 | /bin/bash
          echo $hc3013 | jq -r .i9154 | /bin/bash
          echo $pnwav1475 | jq -r .ah8 | /bin/bash
          echo $nql3 | jq -r .qtnc8 | /bin/bash
          echo $hnva1930 | jq -r .th65811 | /bin/bash
          echo $opnoo51918 | jq -r .d55721 | /bin/bash

